name: apibtc

services:

  btc:
    build:
      context: ../..
      dockerfile: docker/btc/build_btc.Dockerfile

    restart: on-failure
    ports:
      - 18332:18332
      - 28332:28332
      - 28333:28333
    volumes:
      - ./data/btc:/app/btc/:Z
      - ./conf.local/btc/bitcoin.conf:/app/btc/bitcoin.conf:ro
    logging:
      driver: local
      options:
        max-size: "100m"

  lnd:
    build:
      context: ../..
      dockerfile: docker/lnd/build_lnd.Dockerfile

    restart: on-failure
    ports:
      - 9734:9734
      - 11009:11009
      - 8180:8180
    volumes:
      - ./data/lnd:/app/lnd/:Z
      - ./conf.local/lnd/lnd.conf:/app/lnd/lnd.conf:ro
      - ./conf.local/lnd/password.txt:/secret/password.txt:ro
    logging:
      driver: local
      options:
        max-size: "100m"

  api:
    build:
      context: ../..
      dockerfile: docker/apibtc/build_apibtc.Dockerfile

    restart: on-failure
    ports:
      - 7101:80
    volumes:
      - ./data/wallet/:/app/apibtc/:Z
      - ./conf.local/wallet/wallet.conf:/app/apibtc/wallet.conf:ro
      - ./data/lnd/:/app/lnd/:ro
      - ./data/btc:/app/btc/:ro
    logging:
      driver: local
      options:
        max-size: "100m"

  db:
    image: postgres:17.4-bookworm
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=apibtc
      - POSTGRES_USER=apibtc
      - POSTGRES_DB=apibtc
      - PGDATA=/var/lib/postgresql/data/pgdata  
    volumes:
      - ./data/db:/var/lib/postgresql/data:Z
    logging:
      driver: local
      options:
        max-size: "100m"

networks:
  default:
    name: apibtc
    driver: bridge

