name: Build AIO Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main


defaults:
  run:
    shell: pwsh

jobs:


  build-and-push-aio:
    runs-on: ubuntu-latest
    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3
      - # login to Docker Hub using the secrets provided
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # build the container image and push it to Docker Hub
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./docker/aio/build_aio.Dockerfile
          push: true
          tags: awazcognitum/aio:latest



