name: Publish to NPM

on:
  push:
    branches: [ "main" ]

env:
  RepoDirectory: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: cd ${{ env.RepoDirectory }}/javascript && npm ci
      
      - name: Publish package to NPM
        run: cd ${{ env.RepoDirectory }}/javascript && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
